language: python
os:
- linux
python:
- 2.7
- 3.6
sudo: false
install:
- pip install -r requirements.txt
script:
- python -m espatools test
notifications:
  email:
    recipients:
    - info@pvgeo.org
    on_success: never
    on_failure: never
deploy:
  provider: pypi
  user: pvgeosupport
  password:
    secure: QU6gmxAzeHx7l9iK6LgP2mb0XqcDy4+KnLcOTHnvplinWfA5jxxLiJJGwTL8sCzoIhiZuyg7rYriyYxq0ZgE8Z9yRbcp7lGEBXJrLAS046UHpprvjBJ0GDdmVbu2d63Wi1gO+22lZNrRg+QoXbmYq4Fq0WxcFNoRUqJAC58HtEvNU9XWudxdidQAWVtYHdvnHrHQKM57f3JxLCewcH1n0C+TJSTCLOW/189l1M4v4kILyqDKxepYSDqwdGRRBiSH4VlMaoRxbQsLgEtnvskDmkNJCCSzVQmC21d/NComyZ+kJQDzqyxd37rHvDu63N9u22/zM/pf/661Mv/MYIhpe7G+Uy8Q4Xudv9W39UGZdi+feDPHuPGB/EFvZDDeGe46+bTlCujaDD/gOU+D2QQW9rxeVJJ98r08pBwMAb5WOetLqZlMUcPXp/W6myqYfn/ZKCJFJUK2RxMaSsIw1/f5jerdkpH4xauqqcthVlw8Q8CSjXNtauq0E6QtwxPs70N8RyjSnYnRco78muraC1d5FnovAxMRrUCuC3wjLon3QDy/7vgKmjfu+Jm22TeYlfPg1FAUQ/Y2o9lyc26y491KwPsE5FZD8wIBZLvgUZbMKzWqXwL72G2IIFXxl99HMhqKuJzmnz+7epv3akUkYwAnc0FEBr/ry4u78XuAuUYB7fY=
  on:
    repo: OpenGeoVis/espatools
    branch: master
    tags: true
    python: 2.7
